[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.147.8"
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview.environment]
  HUGO_ENV = "production"

[context.branch-deploy.environment]
  HUGO_ENV = "production"

# Optional: Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Optional: Redirects
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301